default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  template: template0

development:
  <<: *default
  database: gmartincor_development

test:
  <<: *default
  database: gmartincor_test

production:
  <<: *default
  database: gmartincor_production
