default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: gmartincor
  password: tomatito    # O usa <%= ENV['DATABASE_PASSWORD'] %> si estás usando variables de entorno
  pool: 5
  template: template0    # Especifica que se use template0

development:
  <<: *default
  database: gmartincor_development

test:
  <<: *default
  database: gmartincor_test

production:
  <<: *default
  database: gmartincor_production
  username: gmartincor
  password: tomatito
